export const CustomerBookData = [
  {
    id: 1,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 2,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 3,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },

  {
    id: 4,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 5,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 6,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 7,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 8,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 9,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 10,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
  {
    id: 11,
    date: "17-Nov-22",
    agentID: "agent.1120",
    enterDate: "11-Nov-22",
    loanID: "6686287",
    disbursementDate: "08-May-22",
    borrowerName: "Tawakalt Hassan",
    email: "devudosinachi@gmail.com",
    phoneNumber: "09087654321",
    reasonForNonPayment: "Repayment Issue",
    promiseToPay: "Yes",
    comment: "Promise to make part payment",
  },
];
